### ISSUE TITLE
simplified policy yml

### ISSUE THREAD

**Issue by kazvictor** [ca-api-gateway/gateway-developer-plugin#102]
```yaml
all:
  - set-variable:
       name: "my-variable"
       value: "my-value"
  - template-response:
       body: "${my-variable}"
```
