### ISSUE TITLE
named services

### ISSUE THREAD

**Issue by kazvictor** [ca-api-gateway/gateway-developer-plugin#48]
Currently this is an example serving configuration:
```yaml
gateway-solution/another-service.xml:
  url: "/another-service-example"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
```

The service does not have a name, it is associated with a policy located at `gateway-solution/another-service.xml`.

In order to enable multiple services to use the same policy name it so that services are named. Update the service configuration to be: 
```yaml
my-service:
  policy: gateway-solution/some-policy.xml:
  url: "/another-service-example"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
folder/my-other-service:
  policy: gateway-solution/some-policy.xml:
  url: "/another-service-example"
  httpMethods:
  - "DELETE"
  - "GET"
  - "PUT"
  properties:
    myProperty:"123"
```

In the above both services use the same policy XML but have different names and properties.

**Acceptance Criteria:**
* new service configuration does not have to be compatible with the old one
* When services are exported using the export plugin their name is the full service path minus the export folder path
* When services are built using the developer plugin they are put into a folder based on their name
  * Prepend the project name as the root folder. For example the service from the configuration above with the name `folder/my-other-service` would be in this location on a gateway if the project name is `gateway-solution`: `Root Folder -> gateway-solution -> folder -> my-other-service`

Known Issue:
* After a build, the policy reference information will be lost on the Gateway. During export, the policy path should be the path of the service itself including the export folder path.
